apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
  {{- include "webapp.labels" . | nindent 4 }}
data:
  index.html: |
    This is a VERY VERY new feature No.3<p>
    This is version {{ .Chart.AppVersion }} of our app, running in {{ .Values.appType }}


